In [1]:
from adam.core.computations import KinDynComputations
from adam.geometry import utils
import numpy as np
import casadi as cs
import gym_ignition_models
from adam.core.computationsWithHardwareParameters import  KinDynComputationsWithHardwareParameters

In [2]:
def SX2DM(sx):
    return cs.DM(sx)

In [3]:

urdf_path ='/home/carlotta/iit_ws/ergocub-gazebo-simulations/models/stickBot/model.urdf'
# urdf_path = gym_ignition_models.get_model_file("iCubGazeboV2_5")
# The joint list
joints_name_list = [
    'torso_pitch', 'torso_roll', 'torso_yaw', 'l_shoulder_pitch',
    'l_shoulder_roll', 'l_shoulder_yaw', 'l_elbow', 'r_shoulder_pitch',
    'r_shoulder_roll', 'r_shoulder_yaw', 'r_elbow', 'l_hip_pitch', 'l_hip_roll',
    'l_hip_yaw', 'l_knee', 'l_ankle_pitch', 'l_ankle_roll', 'r_hip_pitch',
    'r_hip_roll', 'r_hip_yaw', 'r_knee', 'r_ankle_pitch', 'r_ankle_roll'
]
link_name_list = ['l_hip_3']
joint_modified_list = ['l_hip_yaw']
# Specify the root link
root_link = 'root_link'
kinDyn =KinDynComputationsWithHardwareParameters(urdf_path, joints_name_list,link_name_list,joint_modified_list, root_link)

In [4]:
# Set joints and base informations
xyz = (np.random.rand(3) - 0.5) * 5
rpy = (np.random.rand(3) - 0.5) * 5
H_b = utils.H_from_PosRPY(xyz, rpy)
v_b = (np.random.rand(6) - 0.5) * 5
s = (np.random.rand(len(joints_name_list)) - 0.5) * 5
s_dot = (np.random.rand(len(joints_name_list)) - 0.5) * 5
density = 0.1 
lenght_multiplier = 1

In [5]:
[M, J_cmm] = kinDyn.crba()
M(H_b, s, density, lenght_multiplier)

[[0.0124736  0.         0.        ]
 [0.         0.01236479 0.        ]
 [0.         0.         0.01      ]]
3.4727550000000003
[0.0, 0.0, 0.0]
[0.0, 0.0, -1.5707963267948966]
[[0.01053566 0.         0.        ]
 [0.         0.01       0.        ]
 [0.         0.         0.01      ]]
2.356315
[0.0, 0.0, 0.075]
[0.0, 0.0, -1.5707963267948966]
[[0.01 0.   0.  ]
 [0.   0.01 0.  ]
 [0.   0.   0.01]]
1.889537
[0.0, 0.0, 0.0669]
[0.0, 0.0, -1.5707963267948966]
[[0.07501887 0.         0.        ]
 [0.         0.07211585 0.        ]
 [0.         0.         0.05486878]]
7.484841000000002
[0.0, 0.0, 0.09138800000000014]
[0.0, 0.0, -1.5707963267948966]
[[0.01 0.   0.  ]
 [0.   0.01 0.  ]
 [0.   0.   0.01]]
1.45988
[0.0, -0.07445, 0.0]
[-0.19999999999999998, 1.5549999999999993, -1.840815419889917]
[[0.01 0.   0.  ]
 [0.   0.01 0.  ]
 [0.   0.   0.01]]
0.322126
[0.0, 0.0, 0.0]
[-0.07156446033079357, 0.06196992338505823, -1.8462350402422587]
[[0.01 0.   0.  ]
 [0.   0.01 0.  ]
 [0.   0.   0.01]]
0.2

NotImplementedError: Wrong number or type of arguments for overloaded function 'mtimes'.
  Possible prototypes are:
    mtimes([Sparsity])
    mtimes([DM])
    mtimes([SX])
    mtimes([MX])
    mtimes(Sparsity,Sparsity)
    mtimes(DM,DM)
    mtimes(SX,SX)
    mtimes(MX,MX)
  You have: '(SX,[[SX|int]])'
